from .color import cluster

econ_words = [
    "Interest Rates",
    "Inflation",
    "Stock Market",
    "Bonds",
    "Personal Finance",
    "Budgeting",
    "Retirement Planning",
    "Investment Strategies",
    "Mutual Funds",
    "Taxation",
    "Economic Indicators",
    "Financial Planning",
    "Credit Management",
    "Risk Management",
    "Wealth Management",
    "Portfolio Diversification",
    "Capital Markets",
    "Exchange Rates",
    "Financial Literacy",
    "Real Estate Investment",
    "Commodities",
    "Derivatives",
    "Entrepreneurial Finance",
    "Corporate Finance",
    "Mergers and Acquisitions",
    "Banking",
    "Cryptocurrency",
    "Financial Markets",
    "Asset Allocation",
    "Fiscal Policy",
    "Monetary Policy",
    "Capital Budgeting",
    "Hedge Funds",
    "Venture Capital",
    "Insurance",
    "Estate Planning",
    "Financial Regulations",
    "Credit Scores",
    "Cash Flow Management",
    "IPOs (Initial Public Offerings)",
    "Dividend Investing",
    "Annuities",
    "Financial Analyst",
    "Economic Growth",
    "Exchange-Traded Funds (ETFs)",
    "Valuation",
    "Foreign Exchange (Forex)",
    "Investment Banking",
    "Risk Assessment",
    "Microfinance"
]
emotion_words = [
    "Happy",
    "Sad",
    "Angry",
    "Joyful",
    "Anxious",
    "Excited",
    "Content",
    "Frustrated",
    "Surprised",
    "Calm",
    "Energetic",
    "Bored",
    "Confident",
    "Hopeful",
    "Loved",
    "Lonely",
    "Relieved",
    "Nervous",
    "Guilt",
    "Proud",
    "Enthusiastic",
    "Grateful",
    "Indifferent",
    "Optimistic",
    "Disappointed",
    "Jealous",
    "Fearful",
    "Insecure",
    "Apathetic",
    "Awe",
    "Tender",
    "Resentful",
    "Regretful",
    "Apprehensive",
    "Amused",
    "Vulnerable",
    "Empowered",
    "Repulsed",
    "Serene",
    "Hurt",
    "Melancholic",
    "Defiant",
    "Humbled",
    "Yearning",
    "Satisfied",
    "Skeptical",
    "Irritated",
    "Overwhelmed",
    "Blissful"
]
for node in cluster(emotion_words):
    print()
    print(node.angles_str)
